[package]
name = "humanitl-rules"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
humanitl-core.workspace = true

chrono.workspace = true
globset.workspace = true
regex.workspace = true
serde.workspace = true
serde_yaml_ng.workspace = true
thiserror.workspace = true
