include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/core/ipc/generated/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_relative_imports: true
    public_member_api_docs: true
    always_declare_return_types: true
    avoid_print: true
