[package]
name = "humanitl-findings"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
humanitl-core.workspace = true
aho-corasick.workspace = true
brotli.workspace = true
flate2.workspace = true
regex.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
flate2.workspace = true
